In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [9]:
df = pd.read_csv("training.csv")

display(df)

display(df.describe())

print('Data types of each column:')
display(df.info())

print('Missing values per column:')
display(df.isna().sum())

,id,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday,sales
0,425390,366,4,2013-04-18,517,1,0,0,0,4422
1,291687,394,6,2015-04-11,694,1,0,0,0,8297
2,411278,807,4,2013-08-29,970,1,1,0,0,9729
3,664714,802,2,2013-05-28,473,1,1,0,0,6513
4,540835,726,4,2013-10-10,1068,1,1,0,0,10882
...,...,...,...,...,...,...,...,...,...,...
640835,359783,409,6,2013-10-26,483,1,0,0,0,4553
640836,152315,97,1,2014-04-14,987,1,1,0,0,12307
640837,117952,987,1,2014-07-07,925,1,0,0,0,6800
640838,435829,1084,4,2014-06-12,725,1,0,0,0,5344
640839,305711,695,7,2015-05-03,0,0,0,0,0,0

,id,store_ID,day_of_week,nb_customers_on_day,open,promotion,school_holiday,sales
count,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000
mean,355990.675084,558.211348,4.000189,633.398577,0.830185,0.381718,0.178472,5777.469011
std,205536.290268,321.878521,1.996478,464.094416,0.375470,0.485808,0.382910,3851.338083
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,178075.750000,280.000000,2.000000,405.000000,1.000000,0.000000,0.000000,3731.000000
50%,355948.500000,558.000000,4.000000,609.000000,1.000000,0.000000,0.000000,5746.000000
75%,533959.250000,837.000000,6.000000,838.000000,1.000000,1.000000,0.000000,7860.000000
max,712044.000000,1115.000000,7.000000,5458.000000,1.000000,1.000000,1.000000,41551.000000

Data types of each column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640840 entries, 0 to 640839
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   640840 non-null  int64
 1   store_ID             640840 non-null  int64
 2   day_of_week          640840 non-null  int64
 3   date                 640840 non-null  object
 4   nb_customers_on_day  640840 non-null  int64
 5   open                 640840 non-null  int64
 6   promotion            640840 non-null  int64
 7   state_holiday        640840 non-null  object
 8   school_holiday       640840 non-null  int64
 9   sales                640840 non-null  int64
dtypes: int64(8), object(2)
memory usage: 48.9+ MB

None

Missing values per column:

id                     0
store_ID               0
day_of_week            0
date                   0
nb_customers_on_day    0
open                   0
promotion              0
state_holiday          0
school_holiday         0
sales                  0
dtype: int64

# Data cleaning & prepare - Feature Engineering

In [10]:
df = df.drop('id', axis=1)

In [11]:
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

df = df.drop('date', axis=1)

df = pd.get_dummies(df, columns=['state_holiday'])

df = df.dropna()

# X/Y MATRIX  Train / Test

In [12]:

X = df.drop('sales', axis=1)
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression

In [13]:
lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred_train = lr.predict(X_train)
y_pred_val = lr.predict(X_test)

r2_train = r2_score(y_train, y_pred_train)
r2_val = r2_score(y_test, y_pred_val)

print(f"R2 Score Train : {r2_train:.4f}")
print(f"R2 Score Test : {r2_val:.4f}")

R2 Score Train : 0.8550
R2 Score Test : 0.8523

# Models train & evaluate

In [ ]:
%pip install xgboost
from xgboost import XGBRegressor

In [5]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

In [18]:
models = {
    "Linear Regression": LinearRegression(),
    "KNN Regression": KNeighborsRegressor(n_neighbors=5),
    "Decision Tree": DecisionTreeRegressor(max_depth=5, random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=42) 
}

for name, model in models.items():
    
    model.fit(X_train, y_train)
    
    y_pred_train = model.predict(X_train)
    y_pred_val = model.predict(X_test) 
    
    r2_train = r2_score(y_train, y_pred_train)
    r2_val = r2_score(y_test, y_pred_val) 
    
    print(f"--- {name} ---")
    print(f"R2 Train : {r2_train:.4f} | R2 Test : {r2_val:.4f}\n")

--- Linear Regression ---
R2 Train : 0.8550 | R2 Test : 0.8523

--- KNN Regression ---
R2 Train : 0.9239 | R2 Test : 0.8830

--- Decision Tree ---
R2 Train : 0.8584 | R2 Test : 0.8561

--- Random Forest ---
R2 Train : 0.9894 | R2 Test : 0.9416

# Real data processing

In [ ]:
real_data = pd.read_csv("REAL_DATA.csv")

df_real = real_data.copy()

print('Data types of each column:')
display(df_real.info())

Data types of each column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71205 entries, 0 to 71204
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                71205 non-null  int64
 1   store_ID             71205 non-null  int64
 2   day_of_week          71205 non-null  int64
 3   date                 71205 non-null  object
 4   nb_customers_on_day  71205 non-null  int64
 5   open                 71205 non-null  int64
 6   promotion            71205 non-null  int64
 7   state_holiday        71205 non-null  object
 8   school_holiday       71205 non-null  int64
dtypes: int64(7), object(2)
memory usage: 4.9+ MB

None

# DATA CLEANING & FEATURE ENGINEERING

In [ ]:

# Drop the 'id' column as it has no predictive value
X_real = df_real.drop('index', axis=1)

X_real['date'] = pd.to_datetime(X_real['date'], format='mixed', errors='coerce')
X_real['year'] = X_real['date'].dt.year
X_real['month'] = X_real['date'].dt.month
X_real['day'] = X_real['date'].dt.day

# Drop the original 'date' column
X_real = X_real.drop('date', axis=1)

# d. Handle missing values with 0.
X_real = X_real.fillna(0)

# Convert categorical variables One-Hot Encoding
X_real = pd.get_dummies(X_real, columns=['state_holiday'])

X_real = X_real.reindex(columns=X_train.columns, fill_value=0)


# PREDICTION WITH THE BEST MODEL

best_model = models["Random Forest"] 
sales_predictions = best_model.predict(X_real)


# APPEND 'SALES' COLUMN AND EXPORT

real_data['sales'] = sales_predictions
real_data['sales'] = real_data['sales'].round().astype(int)
real_data.to_csv("G3.csv", index=False)

print("File G3.csv created. Sales column has been added.")

File Group3.csv created. Sales column has been added.